return {
    "xiyaowong/transparent.nvim",
    lazy = false,
    keys = {
        -- Transparency
        vim.keymap.set("n", "yob", "<cmd>TransparentToggle<cr>", { silent = true }),
        desc = "Toggle transparency",
    },
    opts = {
        groups = { -- table: default groups
            "Normal",
            "NormalNC",
            "Comment",
            "Constant",
            "Special",
            "Identifier",
            "Statement",
            "PreProc",
            "Type",
            "Underlined",
            "Todo",
            "String",
            "Function",
            "Conditional",
            "Repeat",
            "Operator",
            "Structure",
            "LineNr",
            "NonText",
            "SignColumn",
            "CursorLineNr",
            "EndOfBuffer",
        },
        extra_groups = {},
        exclude_groups = {},
    },
}
